### PR TITLE
Update to GNOME 44 runtime

### PR DESCRIPTION
**Pull request by tim-gromeyer**
I tested it, it works

### CODE REVIEW

**Comment by sonnyp** [comment]
Thanks but that needs to happen upstream in the Oh My SVG repo first and I'll make a release.

**Comment by tim-gromeyer** [comment]
> Thanks but that needs to happen upstream in the Oh My SVG repo first and I'll make a release. 

So you want to port it to gtk4 and libadwaita? If so, nice!

But can't we still use the Gnome 44 runtime for flatpak? I mean, it works. Just the libs are updated. This project is the only one using the Gnome 43 runtime, which is a waste of memory

**Comment by sonnyp** [comment]
Upstream first :)

I don't want to take the risk that something breaks and spend my time debugging / hotfix. 

GNOME 45 fixes a critical bug in Oh My SVG anyway and is 2 weeks away, so it makes sense to bump there directly.

You're very welcome to contribute to Oh My SVG if you want things to move faster :pray:

**Comment by tim-gromeyer** [comment]
> You're very welcome to contribute to Oh My SVG if you want things to move faster :pray: 

Hmm, it's JavaScript, and I hate JavaScript. If it was c++ I would help... but it isn't

**Comment by sonnyp** [comment]
There is no JavaScript to write, just port to GNOME 45.

flathub-beta org.gnome.Platform//beta45

it's essentially what you did here

Oh My SVG is already on GTK4 / libadwaita

**Comment by tim-gromeyer** [comment]
> There is no JavaScript to write, just port to GNOME 45.

Oh, perfect!

> flathub-beta org.gnome.Platform//beta45
> 
> it's essentially what you did here

I changed 43 to 44 and tested it 😅 that's everything I did

But I think it's faster if you do it, I would produce a mess when installing all the Javascript tools...

> Oh My SVG is already on GTK4 / libadwaita

Nice, that's why it was looking so good (my question didn't make any sense, lol)

**Pull request closed without merging**
