### PR TITLE
update to runtime version 45, 43 is deprecated

### PR DESCRIPTION
**Pull request by dominikzogg**

### CODE REVIEW

**Comment by dominikzogg** [comment]
@sonnyp seems to work (opened and saved an svg successfully)

**Comment by tim-gromeyer** [comment]
See #2 

Edit: Let's see what he says to gnome 45

**Comment by dominikzogg** [comment]
@tim-gromeyer i haven't guessed that there is a closed PR ;-)

**Comment by dominikzogg** [comment]
@tim-gromeyer @sonnyp works fine with gnome 45

**Comment by sonnyp** [comment]
https://github.com/flathub/re.sonny.OhMySVG/pull/2

**Comment by dominikzogg** [comment]
@sonnyp when you close this PR its only a question of time you'll get a new one, no one will ever search for a closed PR like #2 or this one.

**Comment by sonnyp** [comment]
I don't mind. It takes me one click to close a PR.

I took time to explain what to do here https://github.com/flathub/re.sonny.OhMySVG/pull/2

It's literary the same as in here.

**Pull request closed without merging**
